### PR TITLE
Fixed local dev server link

### PR DESCRIPTION
**Pull request by kylethorne**

### CODE REVIEW

**Review by tspearconquest — APPROVED** [review]
Related to #70

**Comment by tspearconquest** [comment]
I'm not a project approver but this looks good to me, so I filed https://github.com/tenable/terrascan/issues/1384 to try to get the devs attention to approve and merge this.

**Review by gaurav-gogia — APPROVED** [review]

**Review by gaurav-gogia — CHANGES_REQUESTED** [review]
Looks like there are some conflicts. Please resolve them.

**Review by gaurav-gogia — APPROVED** [review]
resolved conflicts

**Pull request merged**
